### ISSUE TITLE
Virus Total Report. flagged AMDownloader-1.3.2.0-setup.exe as malicious

### ISSUE THREAD

**Issue by SiddharthSharma16923** [antikmozib/AM-Downloader#10]
i scanned your installer downloaded from here(releases)
and the result https://www.virustotal.com/gui/file/61737657e16080e40254b6bb792661ef097ae590ba9bfc0365ce2a72db8582e5/detection

PLS Explain, I cant try this app before you clarify this(but i want to try😟)

`*file named AMDownloader-1.3.2.0-setup.exe`

`SHA-256:61737657E16080E40254B6BB792661EF097AE590BA9BFC0365CE2A72DB8582E5`

**Comment by antikmozib** [comment]
That's a false positive. But to be 100% safe from your side, you can download the portable version, run it in a VM and test it out.

**Comment by SiddharthSharma16923** [comment]
🤔cant be sure....hmm,,,. i think virustotal is a bit .. over sensitive
