### ISSUE TITLE
Add ability to download Youtube videos?

### ISSUE THREAD

**Issue by raelb** [antikmozib/AM-Downloader#14]
Hi,
Thanks for your project. Very nicely done.
It would be cool if you could integrate with this c# library to download Youtube videos as well:
https://github.com/Tyrrrz/YoutubeExplode
https://github.com/Tyrrrz/YoutubeDownloader

There may be some difficulty in the code, since a Youtube download could contain 2 files - audio & video.
You could restrict downloads to a single file (only muxed streams or only audio), or else make other changes to the code.

The YoutubeDownloader does work ok, but it does not allow to resume downloads, and does not give as much control as AM-Downloader.

I'm curious what are your thoughts?

Thanks

**Comment by antikmozib** [comment]
Hi. I had a look into it but unfortunately the work required would be fairly extensive in terms UI updates, download management and ongoing maintenance.
