### ISSUE TITLE
Improve INotifyPropertyChanged

### ISSUE THREAD

**Issue by Ghislain1** [antikmozib/AM-Downloader#17]
**Describe the bug**
Extended INotifyPropertyChanged to remove boilerplate code  e.g. RaisePropertyChanged() method

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Windows version: [e.g. 11 22H2]
 - AM Downloader version: [e.g. 1.3.2]

**Comment by antikmozib** [comment]
Can you please provide a bit more details on the issue?
