### ISSUE TITLE
The MSI installer won't install

### ISSUE THREAD

**Issue by rayman3003** [antikmozib/AM-Downloader#7]
Despite I downloaded & installed ASP.NET Core Runtime 3.1.14 from this link:

https://dotnet.microsoft.com/download/dotnet/3.1

It still shows this error:

![555](https://user-images.githubusercontent.com/17022701/116901161-d53e7980-ac4e-11eb-9db6-79554e5f7c1e.jpg)

Please add an archived zip version for download.

**Comment by antikmozib** [comment]
I've published a new release using InnoSetup. Should work now. Please try it out.

**Comment by rayman3003** [comment]
Thank u. It worked, but after installation of ".NET Core 3.1 **Desktop** Runtime".
