### ISSUE TITLE
Some suggestions from a downloader

### ISSUE THREAD

**Issue by rayman3003** [antikmozib/AM-Downloader#8]
Hi. I just tried AM-Downloader, But I found it lacking some features. Please take a look at these suggestions:

1- Importing & exporting list of download links to & from a text file.

2- Ability to shut down or hibernate the PC, after completion of all downloads.

3- An ability to move links to up (& top) & down (& bottom) of the list.

4- Ability to add mirror link(s) to the downloading links.

5- A windows in option to save username & password for login-required websites.

6- Option to deselect the non-preferred columns (Name - Type - Status - ...)

7- Adding drag or drop option from browser to the main page of downloader.

8- Having a drag-an-drop small windows.

9- Ability to monitoring the clipboard for the links of pre-defined extensions.

10- Right click -> "stop all" & "start all".

11- Option to choose the number of connections per each link. from 1 to 32.

12- Option for adding proxy servers (& it's username & password).

13- Option to choose the number of retries for each link. from 1 to 999.

**Comment by rayman3003** [comment]
Closed? Won't Fix? WTH?! Your app won't reach anywhere.

**Comment by antikmozib** [comment]
I didn't create this app for it to go somewhere. If you don't like it, use something else, or better yet, make your own.

**Comment by rayman3003** [comment]
If I knew programming, I would make the best download manager on earth, but unfortunately I can't.

Maybe u made this app for fun. Have fun with your funny app.

**Comment by antikmozib** [comment]
If you have any specific issues with the program (e.g. bugs or a simple feature request), please feel free to make a new issue. I'd highly appreciate it if you'd stop making irreverent and abusive comments. Please take into account the fact that I can only work on this in my very limited free time.

**Comment by rayman3003** [comment]
I took my time & used my years of experience of downloading, to write those suggestions & help your app to improve.

But u ignored all of those efforts & closed the suggestions, without any reason.

No, I don't want an incomplete download manger. I won't bother u again.

**Comment by antikmozib** [comment]
As much as I appreciate your effort in downloading and reviewing this program, please understand that your feature request was well beyond the scope of what will ever be possible in this application (and indeed, it was well beyond the scope of typical GitHub issues conversations) - hence I closed the issue. I should've mentioned this while closing and I convey my apologies for this.
