### ISSUE TITLE
I like your app😊, and i have some ideas/suggestion for you

### ISSUE THREAD

**Issue by SiddharthSharma16923** [antikmozib/AM-Downloader#9]
i was looking desperately for some good download manager... although idm* is excellent, but i decided to abandon it bcz it does something to my proxies(bcz of the message i get after uninstalling it "pls reboot or internet wont work properly")
i don't like any app(and most other users) that indicates that it did "something" that might hamper with the working of the internal components/functions of windows os

WHAT AM I ASKING FOR?
i am not asking you to "do not include any advanced features and keep it simple"
i am saying all that is "please always give us a choice",,, i don't want any "forced" ....chrome integration(forced..as in case of idm... it installs automatically... i hate that)

and pls keep this app as lite as possible(just like another excellent app  Picotorrent, it looks really nice and clean, i wonder if you can take inspiration from that .. it is on github ..take a look [Picotorrent at github](https://github.com/picotorrent/picotorrent) )...

as all the other download managers(exclude idm) are above ~70 Mb..
i am like "maeen ,, i just asked for the resumable download capability , in a sophisticated UI.. the heck are you packing in the 80MB app(malware?)

you would be getting a lots of suggestions regarding improvement of your app😊 from me

*i mentioned the idm story , bcz i am hinting something about some things that you shall avoid

**Comment by antikmozib** [comment]
Thank you for your suggestions. Yes, that was indeed my motivation behind this app - to keep it simple. It is very motivating to know you find this app useful :)
